### ISSUE TITLE
v0.3.10 error darwin x64

### ISSUE THREAD

**Issue by marcomarinodev** [microsoft/vscode-java-installer#101]
:warning:Please attach **$TMPDIR/vscode-java-installer/log.txt** for more details.
version: 0.3.10
env:
```
JAVA_HOME: undefined
PATH:
/usr/bin
/bin
/usr/sbin
/sbin
JDKs:
/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home	DefaultLocation
/Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home	DefaultLocation
/Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home	DefaultLocation
```
log:
```
[23:51:02] Configure Java Settings
[23:51:02] Error occurred
[23:51:02] Error: EPERM: operation not permitted, mkdir '/Users/marcomarino/Library/Containers/com.apple.Safari/Data/Library/Application Support/Code'

```

**Comment by Eskibear** [comment]
> [23:51:02] Error: EPERM: operation not permitted, mkdir '/Users/marcomarino/Library/Containers/com.apple.Safari/Data/Library/Application Support/Code'

For some reason, it was attempting to extract VS Code to a wrong place.

To work it around, you can install [VS Code](https://code.visualstudio.com/) by your own. And with [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack), it's all set. Please let me know if it works.
