### ISSUE TITLE
Installer v0.3.1 error

### ISSUE THREAD

**Issue by Leenox** [microsoft/vscode-java-installer#109]
version: 0.3.1
env:
```
os: win32
arch: x64
PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[00:53:00] AdoptOpenJDK-11-x64
[00:53:00] StatusCodeError: 404 - "Not found"
[00:53:00] Retry downloading ... [1]
[00:53:01] StatusCodeError: 404 - "Not found"
[00:53:01] Retry downloading ... [2]
[00:53:02] Error occurred
[00:53:02] Failed to download JDK.

```
Please attach **%TEMP%\vscode-java-installer\log.txt** for more details.

**Comment by Eskibear** [comment]
@Leenox Thanks for reporting this. Seems AdoptOpenJDK v2 API is unstable, we have reached to the team. For the moment, you can manually download JDK 11 from https://adoptopenjdk.net/ , and re-run the latest version of our installer https://aka.ms/vscode-java-installer-win

**Comment by Eskibear** [comment]
AdoptOpenJDK has fixed this issue.
