### ISSUE TITLE
v0.3.11 error win32 x64

### ISSUE THREAD

**Issue by Frankpig** [microsoft/vscode-java-installer#110]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.11
env:
```
JAVA_HOME: undefined
PATH:
C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services
C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Users\huoyanfang\AppData\Local\Microsoft\WindowsApps

D:\Microsoft VS Code\bin
JDKs:

```
log:
```
[上午10:32:07] AdoptOpenJDK-11-x64
[上午10:38:04] RequestError: Error: read ECONNRESET
[上午10:38:04] Retry downloading ... [1]
[上午11:37:04] Download JDK ... [Completed]
[上午11:37:04] Install JDK
[上午11:37:04] Installing AdoptOpenJDK-11-x64...
[上午11:37:04] Error occurred
[上午11:37:04] Error: Command failed with exit code 1619: C:\Windows\System32\msiexec.exe /i "C:\Users\HUOYAN~1\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\OpenJDK11U-jdk_x64_windows_hotspot_11.0.9_11.msi" MSIINSTALLPERUSER=1 ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v "C:\Users\HUOYAN~1\AppData\Local\Temp\vscode-java-installer\AdoptOpenJDK-MSI.log"
�e�lSb_dk�[ňz�^S0��nx���z�^SX[(W�v^N`O	gCg��[�b�N�^(uz�^�O�^FUT��|��Nnx��ُ/fN*N	gHe�v Windows Installer z�^S0



```

**Comment by Eskibear** [comment]
It looks JDK installer was broken. You can manually download and install JDK 11 from https://adoptopenjdk.net/ , and re-run our installer. Let me know if it works.

**Comment by Eskibear** [comment]
> [上午10:32:07] AdoptOpenJDK-11-x64
[上午10:38:04] RequestError: Error: read ECONNRESET
[上午10:38:04] Retry downloading ... [1]
[上午11:37:04] Download JDK ... [Completed]

BTW it tooks almost ~1 hour... you can download it from Tsinghua University's mirror site if you are in China. https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/11/jdk/x64/windows/

**Comment by Frankpig** [comment]
yeah, I just re-run the installer. It works now. Thx.



发自我的iPhone


------------------ Original ------------------
