### ISSUE TITLE
v0.3.11 error darwin x64

### ISSUE THREAD

**Issue by anniehoshi18** [microsoft/vscode-java-installer#112]
:warning:Please attach **$TMPDIR/vscode-java-installer/log.txt** for more details.
version: 0.3.11
env:
```
JAVA_HOME: undefined
PATH:
/usr/bin
/bin
/usr/sbin
/sbin
JDKs:

```
log:
```
[17:58:48] AdoptOpenJDK-11-x64
[17:58:59] Download JDK ... [Completed]
[17:58:59] Install JDK
[17:59:04] Error occurred
[17:59:04] Error: User did not grant permission.

```

**Comment by Eskibear** [comment]
installing JDK requires admin privilege, please re-try and let me know if it works. Or you can manually install a JDK 11+, e.g. https://adoptopenjdk.net/
