### ISSUE TITLE
v0.3.11 错误 win32 x64

### ISSUE THREAD

**Issue by tanglu1314** [microsoft/vscode-java-installer#123]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.11
env:
```
JAVA_HOME: undefined
PATH:
C:\Program Files (x86)\Microsoft\Edge\Application
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
D:\mingw64\bin
C:\Users\tl\AppData\Local\Microsoft\WindowsApps
D:\Microsoft VS Code\bin
D:\mingw64\bin
%JAVA_HOME%\bin
%JAVA_HOME%\jre\bin

JDKs:

```
log:
```
[下午5:44:44] AdoptOpenJDK-11-x64
[下午6:18:09] Download JDK ... [Completed]
[下午6:18:09] Install JDK
[下午6:18:09] Installing AdoptOpenJDK-11-x64...
[下午6:18:10] Install JDK ... [Completed]
[下午6:18:10] Configure Java Settings
[下午6:18:10] Error occurred
[下午6:18:10] Error: Java Home not found.

```

**Comment by Eskibear** [comment]
VS Code requires JDK 11+ to launch. Your `%JAVA_HOME%` was not set, and it failed to detect a valid JDK, so it was trying installing a JDK 11 for you. 

> [下午6:18:09] Installing AdoptOpenJDK-11-x64...
[下午6:18:10] Install JDK ... [Completed]

It's finished in 1 second, probably not successfully installed.  Please attach %TEMP%\vscode-java-installer\log.txt and %TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log for more details.



For the moment, to work it around, you can manually install a JDK 11, and re-run this installer.  Let me know if it works.
