### ISSUE TITLE
v0.3.13 error win32 x64

### ISSUE THREAD

**Issue by TripleHJEA** [microsoft/vscode-java-installer#145]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.13
env:
```
JAVA_HOME: undefined
PATH:
C:\Program Files\Google\Chrome\Application
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Users\Xiaoyu Hopkins\AppData\Local\Microsoft\WindowsApps

JDKs:

```
log:
```
[2:50:21 PM] AdoptOpenJDK-11-x64
[2:51:04 PM] Download JDK ... [Completed]
[2:51:04 PM] Install JDK
[2:51:04 PM] Installing AdoptOpenJDK-11-x64...
[2:52:33 PM] Error occurred
[2:52:33 PM] Error: Command failed with exit code 1625: C:\WINDOWS\System32\msiexec.exe /i "C:\Users\XIAOYU~1\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\OpenJDK11U-jdk_x64_windows_hotspot_11.0.10_9.msi" MSIINSTALLPERUSER=1 ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v "C:\Users\XIAOYU~1\AppData\Local\Temp\vscode-java-installer\AdoptOpenJDK-MSI.log"
The system administrator has set policies to prevent this installation.



```

**Comment by Eskibear** [comment]
> The system administrator has set policies to prevent this installation.

You can install JDK 11+ [manually](https://adoptopenjdk.net/), and re-run this installer. Let me know if it works.

**Comment by TripleHJEA** [comment]
It didn't work.  I'm already an admin on the computer and this is what it says:


    On Monday, February 22, 2021, 08:10:24 PM CST, Yan Zhang <notifications@github.com> wrote:  
 
 



The system administrator has set policies to prevent this installation.


You can install JDK 11+ manually, and re-run this installer. Let me know if it works.

**Comment by Eskibear** [comment]
Just as the message said, there might be some policy preventing MSI installers. I found some guide on the internet, you may give it a try if necessary. https://kb.vmware.com/s/article/1016563

BTW, VS Code Java requires a JDK with version 11 or higher. It doesn't have to be installed via MSI. If you can manually install one, that's also fine. For example, you can extract JDK from the archive files, and set proper JAVA_HOME by your own. See https://adoptopenjdk.net/installation.html#x64_win-jdk for reference.

**Comment by TripleHJEA** [comment]
Worked.  Thank you!So weird that MS decided to not allow installation even for system admins!
    On Tuesday, February 23, 2021, 09:16:30 PM CST, Yan Zhang <notifications@github.com> wrote:  
 
 


Just as the message said, there might be some policy preventing MSI installers. I found some guide on the internet, you may give it a try if necessary. https://kb.vmware.com/s/article/1016563

BTW, VS Code Java requires a JDK with version 11 or higher. It doesn't have to be installed via MSI. If you can manually install one, that's also fine. For example, you can extract JDK from the archive files, and set proper JAVA_HOME by your own. See https://adoptopenjdk.net/installation.html#x64_win-jdk for reference.
