### ISSUE TITLE
v0.3.13 error darwin x64

### ISSUE THREAD

**Issue by Krypton-DH** [microsoft/vscode-java-installer#152]
:warning:Please attach **$TMPDIR/vscode-java-installer/log.txt** for more details.
version: 0.3.13
env:
```
JAVA_HOME: undefined
PATH:
/usr/bin
/bin
/usr/sbin
/sbin
JDKs:

```
log:
```
[上午8:47:04] AdoptOpenJDK-11-x64
[上午8:49:35] Error: read ETIMEDOUT
[上午8:49:35] Retry downloading ... [1]
[上午8:51:18] RequestError: Error: read ETIMEDOUT
[上午8:51:18] Retry downloading ... [2]
[上午8:53:47] Error: read ETIMEDOUT
[上午8:53:47] fallback to Adopt API v3
[上午8:57:36] RequestError: Error: Client network socket disconnected before secure TLS connection was established
[上午8:57:36] Retry downloading ... [1]
[上午8:58:53] Download JDK ... [Completed]
[上午8:58:53] Install JDK
[上午8:59:02] Error occurred
[上午8:59:02] Error: Command failed: installer -pkg /var/folders/3w/7yrxt1757wg24lk__jvgh6x80000gn/T/vscode-java-installer/binaries/jdk/11/x64/AdoptOpenJDK-11.pkg -target /


```

**Comment by Eskibear** [comment]
It's possible that JDK installer was broken due to networking issue. Can you run below command to check SHA-256 checksum of the JDK installer?

```bash
shasum -a 256 /var/folders/3w/7yrxt1757wg24lk__jvgh6x80000gn/T/vscode-java-installer/binaries/jdk/11/x64/AdoptOpenJDK-11.pkg
```

The workaround is, you can manually download and install a JDK 11+ [here](https://adoptopenjdk.net/), and re-run Java Coding Pack. Let me know if it works.

**Comment by Krypton-DH** [comment]
I installed openjdk@11 through homebrew, then I ran the Coding Pack for Java.app. It is necessary &nbsp;to add openjdk to the PATH manually before run that app. It seems to work well, thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode-java-installer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月10日(星期三) 上午9:36
收件人:&nbsp;"microsoft/vscode-java-installer"<vscode-java-installer@noreply.github.com&gt;;
抄送:&nbsp;"Smile  Againゾ"<3320316895@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode-java-installer] v0.3.13 error darwin x64 (#152)





 
It's possible that JDK installer was broken due to networking issue. Can you run below command to check SHA-256 checksum of the JDK installer?
 shasum -a 256 /var/folders/3w/7yrxt1757wg24lk__jvgh6x80000gn/T/vscode-java-installer/binaries/jdk/11/x64/AdoptOpenJDK-11.pkg
 
The workaround is, you can manually download and install a JDK 11+ here, and re-run Java Coding Pack. Let me know if it works.
