### ISSUE TITLE
v0.3.13 error win32 x64

### ISSUE THREAD

**Issue by johnconnor286** [microsoft/vscode-java-installer#155]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.13
env:
```
JAVA_HOME: undefined
PATH:
C:\Program Files (x86)\Microsoft\Edge\Application
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\Intel\WiFi\bin\
C:\Program Files\Common Files\Intel\WirelessCommon\
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\
C:\Program Files\Microsoft SQL Server\100\Tools\Binn\
C:\Program Files\Microsoft SQL Server\100\DTS\Binn\
C:\Android
C:\Program Files (x86)\Microsoft VS Code\bin
C:\Users\connor\AppData\Local\Microsoft\WindowsApps
C:\Program Files\Bandizip\
C:\Program Files (x86)\Microsoft VS Code\bin
JDKs:

```
log:
```
[下午6:25:13] AdoptOpenJDK-11-x64
[下午6:26:05] Error: read ECONNRESET
[下午6:26:05] Retry downloading ... [1]
[下午6:26:07] Error: read ECONNRESET
[下午6:26:07] Retry downloading ... [2]
[下午6:26:28] Error: read ECONNRESET
[下午6:26:28] fallback to Adopt API v3
[下午6:26:45] Error: read ECONNRESET
[下午6:26:45] Retry downloading ... [1]
[下午6:27:07] Error: connect ETIMEDOUT 52.74.223.119:443
[下午6:27:07] Retry downloading ... [2]
[下午6:28:02] Download JDK ... [Completed]
[下午6:28:02] Install JDK
[下午6:28:02] Installing AdoptOpenJDK-11-x64...
[下午6:28:02] Error occurred
[下午6:28:02] Error: Command failed with exit code 1620: C:\Windows\System32\msiexec.exe /i "C:\Users\connor\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\AdoptOpenJDK-11.msi" MSIINSTALLPERUSER=1 ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v "C:\Users\connor\AppData\Local\Temp\vscode-java-installer\AdoptOpenJDK-MSI.log"
�e�lSb_dk�[ňz�^S0��N�^(uz�^�O�^FUT��|��Nnx��ُ/fN*N	gHe�v Windows Installer z�^S0



```

**Comment by Eskibear** [comment]
> ERROR_INSTALL_PACKAGE_INVALID, 1620, This installation package could not be opened.

It's probably broken due to networking issue. Try downloading [a JDK 11](https://adoptopenjdk.net/) and install it by your own. Then re-run this installer. Please let me know if it works.

**Comment by johnconnor286** [comment]
You are right,thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode-java-installer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月22日(星期一) 上午10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode-java-installer] v0.3.13 error win32 x64 (#155)





  
ERROR_INSTALL_PACKAGE_INVALID, 1620, This installation package could not be opened.
  
It's probably broken due to networking issue. Try downloading a JDK 11 and install it by your own. Then re-run this installer. Please let me know if it works.
