### ISSUE TITLE
How do I perform an update?

### ISSUE THREAD

**Issue by viveksh1** [microsoft/vscode-java-installer#166]
How would I update my Java installation from the Java Coding Pack? Would simply running the installer again work?

**Comment by Eskibear** [comment]
Java Coding Pack detects and install below components if missing:
* JDK version 11 or above, install AdoptOpenJDK 11 if missing.
* VS Code, install VS Code latest stable version.
* VS Code Java Extension Pack, always install latest version.

So re-running Coding Pack for Java will not upgrade your JDK version. You should download and install one by your own. There is a command `Java: Configure Java Runtime` in VS Code which might also be helpful.

**Comment by viveksh1** [comment]
Thanks.
