### ISSUE TITLE
v0.3.13 error win32 x64

### ISSUE THREAD

**Issue by maskercyh** [microsoft/vscode-java-installer#167]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.13
env:
```
JAVA_HOME: D:\Program Files\Java\jdk1.8.0_181
PATH:
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
D:\Program Files (x86)\NetSarang\Xftp 6\
D:\Program Files\ImageMagick-7.0.10-Q16-HDRI
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
D:\Program Files\Git\cmd
C:\Program Files\TortoiseGit\bin
D:\Program Files (x86)\Lua\5.1
D:\Program Files (x86)\Lua\5.1\clibs
D:\Program Files\OpenSSH\bin
C:\Program Files (x86)\NetSarang\Xshell 7\
D:\Program Files (x86)\Nodist\bin
C:\Program Files\dotnet\
D:\Program Files\Python
C:\Users\chen\AppData\Local\Microsoft\WindowsApps
C:\Users\chen\AppData\Local\Programs\Microsoft VS Code\bin
C:\Program Files\Bandizip\
C:\Users\chen\AppData\Roaming\npm
D:\Program Files\php-7.4.6-nts-Win32-vc15-x64
D:\phpstudy_pro\Extensions\composer1.8.5
D:\Program Files (x86)\SSH Communications Security\SSH Secure Shell
D:\Program Files\Java\jdk1.8.0_181\bin
D:\Program Files\Java\jdk1.8.0_181\jre\bin
D:\Program Files (x86)\apache-jmeter-5.4\lib\ext\ApacheJMeter_core.jar
"
D:\Program Files (x86)\apache-jmeter-5.4\lib\jorphan.jar"
D:\Program Files (x86)\apache-jmeter-5.4\lib\logkit-2.0.jar
C:\Program Files (x86)\SSH Communications Security\SSH Secure Shell
D:\phpstudy_pro\Extensions\MySQL8.0.12\bin

JDKs:
D:\Program Files\Java\jdk1.8.0_181	env.JAVA_HOME,env.PATH,WindowsRegistry,WindowsRegistry
```
log:
```
[上午10:37:26] AdoptOpenJDK-11-x64
[上午10:38:07] Download JDK ... [Completed]
[上午10:38:07] Install JDK
[上午10:38:07] Installing AdoptOpenJDK-11-x64...
[上午10:38:07] Error occurred
[上午10:38:07] Error: Command failed with exit code 1620: C:\WINDOWS\System32\msiexec.exe /i "C:\Users\chen\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\AdoptOpenJDK-11.msi" MSIINSTALLPERUSER=1 ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v "C:\Users\chen\AppData\Local\Temp\vscode-java-installer\AdoptOpenJDK-MSI.log"
�e�lSb_dk�[ňz�^S0��N�^(uz�^�O�^FUT��|��Nnx��ُ/fN*N	gHe�v Windows Installer z�^S0



```

**Comment by maskercyh** [comment]
AdoptOpenJDK-MSI.log

=== Verbose logging started: 2021/4/23  10:38:07  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\WINDOWS\SysWOW64\msiexec.exe ===
MSI (c) (64:A8) [10:38:07:537]: Font created.  Charset: Req=134, Ret=134, Font: Req=宋体, Ret=宋体

MSI (c) (64:A8) [10:38:07:537]: Font created.  Charset: Req=134, Ret=134, Font: Req=宋体, Ret=宋体

MSI (c) (64:E4) [10:38:07:560]: Resetting cached policy values
MSI (c) (64:E4) [10:38:07:560]: Machine policy value 'Debug' is 0
MSI (c) (64:E4) [10:38:07:560]: ******* RunEngine:
           ******* Product: C:\Users\chen\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\AdoptOpenJDK-11.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (64:E4) [10:38:07:561]: Client-side and UI is none or basic: Running entire install on the server.
MSI (c) (64:E4) [10:38:07:561]: Grabbed execution mutex.
MSI (c) (64:E4) [10:38:07:607]: Cloaking enabled.
MSI (c) (64:E4) [10:38:07:607]: Attempting to enable all disabled privileges before calling Install on Server
MSI (c) (64:E4) [10:38:07:610]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (30:28) [10:38:07:618]: Running installation inside multi-package transaction C:\Users\chen\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\AdoptOpenJDK-11.msi
MSI (s) (30:28) [10:38:07:618]: Grabbed execution mutex.
MSI (s) (30:30) [10:38:07:621]: Resetting cached policy values
MSI (s) (30:30) [10:38:07:621]: Machine policy value 'Debug' is 0
MSI (s) (30:30) [10:38:07:621]: ******* RunEngine:
           ******* Product: C:\Users\chen\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\AdoptOpenJDK-11.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (s) (30:30) [10:38:07:622]: Note: 1: 2203 2: C:\Users\chen\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\AdoptOpenJDK-11.msi 3: -2147286960 
MSI (s) (30:30) [10:38:07:623]: MainEngineThread is returning 1620
MSI (s) (30:28) [10:38:07:625]: User policy value 'DisableRollback' is 0
MSI (s) (30:28) [10:38:07:625]: Machine policy value 'DisableRollback' is 0
MSI (s) (30:28) [10:38:07:625]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (30:28) [10:38:07:626]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (30:28) [10:38:07:626]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (30:28) [10:38:07:626]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (64:E4) [10:38:07:627]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (64:E4) [10:38:07:628]: MainEngineThread is returning 1620
=== Verbose logging stopped: 2021/4/23  10:38:07 ===





<details>
<summary>log.txt</summary>


info: Started {"timestamp":"2021-04-23T02:19:52.159Z"}
verbose: Ids: {"machineId":"a61fc05a7dc4d8da0c0416bb734491699d32b26cd11abc9c2ced9f910ef2d5c8","sessionId":"83d6c3c5-3a2d-44a2-aae8-4bbf6009243a1619144391822","timestamp":"2021-04-23T02:19:52.160Z"}
info: Started {"timestamp":"2021-04-23T02:19:58.094Z"}
verbose: Ids: {"machineId":"a61fc05a7dc4d8da0c0416bb734491699d32b26cd11abc9c2ced9f910ef2d5c8","sessionId":"5195cac5-9584-4378-9b95-4d2a3711039f1619144397841","timestamp":"2021-04-23T02:19:58.096Z"}
verbose: Packed binaries: {"timestamp":"2021-04-23T02:20:00.195Z"}
verbose: Found JDK {"timestamp":"2021-04-23T02:20:00.200Z"}
verbose: Found JDKs in env.JAVA_HOME {"jdks":["D:\\Program Files\\Java\\jdk1.8.0_181"],"timestamp":"2021-04-23T02:20:00.201Z"}
verbose: Found JDK {"timestamp":"2021-04-23T02:20:00.221Z"}
verbose: Found JDKs in env.PATH {"jdks":["D:\\Program Files\\Java\\jdk1.8.0_181"],"timestamp":"2021-04-23T02:20:00.223Z"}
verbose: Found JDKs in WindowsRegistry {"jdks":["D:\\Program Files\\Java\\jdk1.8.0_181","D:\\Program Files\\Java\\jdk1.8.0_181"],"timestamp":"2021-04-23T02:20:00.354Z"}
verbose: Found JDKs in DefaultLocation {"jdks":[],"timestamp":"2021-04-23T02:20:00.356Z"}
verbose: java_home candidate: {"candidate":{"home":"D:\\Program Files\\Java\\jdk1.8.0_181","sources":["env.JAVA_HOME","env.PATH","WindowsRegistry","WindowsRegistry"],"version":8},"timestamp":"2021-04-23T02:20:00.359Z"}
verbose: Looking for Code stable x64-user in x64 registry: HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall\{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1 {"timestamp":"2021-04-23T02:20:00.360Z"}
verbose: Code stable x64-user is installed. {"timestamp":"2021-04-23T02:20:00.453Z"}
verbose: Installed components: {"vscode":{"homedir":"C:\\Users\\chen\\AppData\\Local\\Programs\\Microsoft VS Code\\","version":"1.55.2"},"jdk":{"name":"JDK","homedir":"D:\\Program Files\\Java\\jdk1.8.0_181","version":"8"},"extensions":[],"timestamp":"2021-04-23T02:20:00.453Z"}
verbose: jdk metadata {"release_name":"jdk-11.0.11+9","release_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.11%2B9","timestamp":"2021-04-21T19:39:38Z","release":true,"binaries":[{"os":"windows","architecture":"x64","binary_type":"jdk","openjdk_impl":"hotspot","binary_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_size":196371089,"checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip.sha256.txt","installer_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_size":173363200,"installer_checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi.sha256.txt","installer_download_count":6840,"version":"11","version_data":{"openjdk_version":"11.0.11+9","semver":"11.0.11+9"},"heap_size":"normal","download_count":7848,"updated_at":"2021-04-21T19:43:13Z"}],"download_count":17400}
verbose: jdk metadata {"release_name":"jdk-11.0.11+9","release_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.11%2B9","timestamp":"2021-04-21T19:39:38Z","release":true,"binaries":[{"os":"windows","architecture":"x64","binary_type":"jdk","openjdk_impl":"hotspot","binary_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_size":196371089,"checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip.sha256.txt","installer_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_size":173363200,"installer_checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi.sha256.txt","installer_download_count":6840,"version":"11","version_data":{"openjdk_version":"11.0.11+9","semver":"11.0.11+9"},"heap_size":"normal","download_count":7848,"updated_at":"2021-04-21T19:43:13Z"}],"download_count":17400}
verbose: jdk metadata {"release_name":"jdk-11.0.11+9","release_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.11%2B9","timestamp":"2021-04-21T19:39:38Z","release":true,"binaries":[{"os":"windows","architecture":"x64","binary_type":"jdk","openjdk_impl":"hotspot","binary_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_size":196371089,"checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip.sha256.txt","installer_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_size":173363200,"installer_checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi.sha256.txt","installer_download_count":6840,"version":"11","version_data":{"openjdk_version":"11.0.11+9","semver":"11.0.11+9"},"heap_size":"normal","download_count":7848,"updated_at":"2021-04-21T19:43:13Z"}],"download_count":17400}
info: JDK downloaded. {"timestamp":"2021-04-23T02:22:34.916Z"}
verbose: Installing JDK with command: {"msiexec":"C:\\WINDOWS\\System32\\msiexec.exe","args":["/i","\"C:\\Users\\chen\\AppData\\Local\\Temp\\vscode-java-installer\\binaries\\jdk\\11\\x64\\AdoptOpenJDK-11.msi\"","MSIINSTALLPERUSER=1","ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith","/passive","/l*v \"C:\\Users\\chen\\AppData\\Local\\Temp\\vscode-java-installer\\AdoptOpenJDK-MSI.log\""],"timestamp":"2021-04-23T02:22:34.926Z"}
error: Command failed with exit code 1620: C:\WINDOWS\System32\msiexec.exe /i "C:\Users\chen\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\AdoptOpenJDK-11.msi" MSIINSTALLPERUSER=1 ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v "C:\Users\chen\AppData\Local\Temp\vscode-java-installer\AdoptOpenJDK-MSI.log"
�e�lSb _dk�[ňz�^S0��N�^(uz�^�O�^FUT��|��Nnx��ُ/f N*N	gHe�v  W i n d o w s   I n s t a l l e r   z�^S0
 
  {"shortMessage":"Command failed with exit code 1620: C:\\WINDOWS\\System32\\msiexec.exe /i \"C:\\Users\\chen\\AppData\\Local\\Temp\\vscode-java-installer\\binaries\\jdk\\11\\x64\\AdoptOpenJDK-11.msi\" MSIINSTALLPERUSER=1 ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v \"C:\\Users\\chen\\AppData\\Local\\Temp\\vscode-java-installer\\AdoptOpenJDK-MSI.log\"","command":"C:\\WINDOWS\\System32\\msiexec.exe /i \"C:\\Users\\chen\\AppData\\Local\\Temp\\vscode-java-installer\\binaries\\jdk\\11\\x64\\AdoptOpenJDK-11.msi\" MSIINSTALLPERUSER=1 ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v \"C:\\Users\\chen\\AppData\\Local\\Temp\\vscode-java-installer\\AdoptOpenJDK-MSI.log\"","exitCode":1620,"stdout":"�e�lSb\u0000_dk�[ň\u000bz�^\u0005S\u00020��\u000eN�^(u\u000bz�^�O�^FUT��|\f��Nnx��ُ/f\u0000N*N\tgHe�v \u0000W\u0000i\u0000n\u0000d\u0000o\u0000w\u0000s\u0000 \u0000I\u0000n\u0000s\u0000t\u0000a\u0000l\u0000l\u0000e\u0000r\u0000 \u0000\u000bz�^\u0005S\u00020\n\u0000\r\u0000","stderr":"","failed":true,"timedOut":false,"isCanceled":false,"killed":false,"timestamp":"2021-04-23T02:22:35.170Z"}
info: Started {"timestamp":"2021-04-23T02:33:40.329Z"}
verbose: Ids: {"machineId":"a61fc05a7dc4d8da0c0416bb734491699d32b26cd11abc9c2ced9f910ef2d5c8","sessionId":"9f825a30-a3e2-4429-89e8-5beeda51806c1619145219939","timestamp":"2021-04-23T02:33:40.331Z"}
verbose: Packed binaries: {"timestamp":"2021-04-23T02:33:42.799Z"}
verbose: Found JDK {"timestamp":"2021-04-23T02:33:42.803Z"}
verbose: Found JDKs in env.JAVA_HOME {"jdks":["D:\\Program Files\\Java\\jdk1.8.0_181"],"timestamp":"2021-04-23T02:33:42.803Z"}
verbose: Found JDK {"timestamp":"2021-04-23T02:33:42.819Z"}
verbose: Found JDKs in env.PATH {"jdks":["D:\\Program Files\\Java\\jdk1.8.0_181"],"timestamp":"2021-04-23T02:33:42.823Z"}
verbose: Found JDKs in WindowsRegistry {"jdks":["D:\\Program Files\\Java\\jdk1.8.0_181","D:\\Program Files\\Java\\jdk1.8.0_181"],"timestamp":"2021-04-23T02:33:42.959Z"}
verbose: Found JDKs in DefaultLocation {"jdks":[],"timestamp":"2021-04-23T02:33:42.962Z"}
verbose: java_home candidate: {"candidate":{"home":"D:\\Program Files\\Java\\jdk1.8.0_181","sources":["env.JAVA_HOME","env.PATH","WindowsRegistry","WindowsRegistry"],"version":8},"timestamp":"2021-04-23T02:33:42.964Z"}
verbose: Looking for Code stable x64-user in x64 registry: HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall\{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1 {"timestamp":"2021-04-23T02:33:42.965Z"}
verbose: Code stable x64-user is installed. {"timestamp":"2021-04-23T02:33:43.063Z"}
verbose: Installed components: {"vscode":{"homedir":"C:\\Users\\chen\\AppData\\Local\\Programs\\Microsoft VS Code\\","version":"1.55.2"},"jdk":{"name":"JDK","homedir":"D:\\Program Files\\Java\\jdk1.8.0_181","version":"8"},"extensions":[],"timestamp":"2021-04-23T02:33:43.063Z"}
verbose: jdk metadata {"release_name":"jdk-11.0.11+9","release_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.11%2B9","timestamp":"2021-04-21T19:39:38Z","release":true,"binaries":[{"os":"windows","architecture":"x64","binary_type":"jdk","openjdk_impl":"hotspot","binary_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_size":196371089,"checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip.sha256.txt","installer_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_size":173363200,"installer_checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi.sha256.txt","installer_download_count":6840,"version":"11","version_data":{"openjdk_version":"11.0.11+9","semver":"11.0.11+9"},"heap_size":"normal","download_count":7848,"updated_at":"2021-04-21T19:43:13Z"}],"download_count":17400}
verbose: jdk metadata {"release_name":"jdk-11.0.11+9","release_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.11%2B9","timestamp":"2021-04-21T19:39:38Z","release":true,"binaries":[{"os":"windows","architecture":"x64","binary_type":"jdk","openjdk_impl":"hotspot","binary_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_size":196371089,"checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip.sha256.txt","installer_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_size":173363200,"installer_checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi.sha256.txt","installer_download_count":6840,"version":"11","version_data":{"openjdk_version":"11.0.11+9","semver":"11.0.11+9"},"heap_size":"normal","download_count":7848,"updated_at":"2021-04-21T19:43:13Z"}],"download_count":17400}
verbose: jdk metadata {"release_name":"jdk-11.0.11+9","release_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.11%2B9","timestamp":"2021-04-21T19:39:38Z","release":true,"binaries":[{"os":"windows","architecture":"x64","binary_type":"jdk","openjdk_impl":"hotspot","binary_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_size":196371089,"checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip.sha256.txt","installer_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_size":173363200,"installer_checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi.sha256.txt","installer_download_count":6840,"version":"11","version_data":{"openjdk_version":"11.0.11+9","semver":"11.0.11+9"},"heap_size":"normal","download_count":7848,"updated_at":"2021-04-21T19:43:13Z"}],"download_count":17400}
info: Started {"timestamp":"2021-04-23T02:37:18.210Z"}
verbose: Ids: {"machineId":"a61fc05a7dc4d8da0c0416bb734491699d32b26cd11abc9c2ced9f910ef2d5c8","sessionId":"41e316eb-ffe9-451b-aaf8-a23509570d001619145437400","timestamp":"2021-04-23T02:37:18.213Z"}
verbose: Packed binaries: {"timestamp":"2021-04-23T02:37:20.165Z"}
verbose: Found JDK {"timestamp":"2021-04-23T02:37:20.169Z"}
verbose: Found JDKs in env.JAVA_HOME {"jdks":["D:\\Program Files\\Java\\jdk1.8.0_181"],"timestamp":"2021-04-23T02:37:20.171Z"}
verbose: Found JDK {"timestamp":"2021-04-23T02:37:20.200Z"}
verbose: Found JDKs in env.PATH {"jdks":["D:\\Program Files\\Java\\jdk1.8.0_181"],"timestamp":"2021-04-23T02:37:20.205Z"}
verbose: Found JDKs in WindowsRegistry {"jdks":["D:\\Program Files\\Java\\jdk1.8.0_181","D:\\Program Files\\Java\\jdk1.8.0_181"],"timestamp":"2021-04-23T02:37:20.402Z"}
verbose: Found JDKs in DefaultLocation {"jdks":[],"timestamp":"2021-04-23T02:37:20.406Z"}
verbose: java_home candidate: {"candidate":{"home":"D:\\Program Files\\Java\\jdk1.8.0_181","sources":["env.JAVA_HOME","env.PATH","WindowsRegistry","WindowsRegistry"],"version":8},"timestamp":"2021-04-23T02:37:20.409Z"}
verbose: Looking for Code stable x64-user in x64 registry: HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall\{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1 {"timestamp":"2021-04-23T02:37:20.410Z"}
verbose: Code stable x64-user is installed. {"timestamp":"2021-04-23T02:37:20.549Z"}
verbose: Installed components: {"vscode":{"homedir":"C:\\Users\\chen\\AppData\\Local\\Programs\\Microsoft VS Code\\","version":"1.55.2"},"jdk":{"name":"JDK","homedir":"D:\\Program Files\\Java\\jdk1.8.0_181","version":"8"},"extensions":[],"timestamp":"2021-04-23T02:37:20.550Z"}
verbose: jdk metadata {"release_name":"jdk-11.0.11+9","release_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.11%2B9","timestamp":"2021-04-21T19:39:38Z","release":true,"binaries":[{"os":"windows","architecture":"x64","binary_type":"jdk","openjdk_impl":"hotspot","binary_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip","binary_size":196371089,"checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip.sha256.txt","installer_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi","installer_size":173363200,"installer_checksum_link":"https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi.sha256.txt","installer_download_count":6840,"version":"11","version_data":{"openjdk_version":"11.0.11+9","semver":"11.0.11+9"},"heap_size":"normal","download_count":7848,"updated_at":"2021-04-21T19:43:13Z"}],"download_count":17400}
info: JDK downloaded. {"timestamp":"2021-04-23T02:38:07.442Z"}
verbose: Installing JDK with command: {"msiexec":"C:\\WINDOWS\\System32\\msiexec.exe","args":["/i","\"C:\\Users\\chen\\AppData\\Local\\Temp\\vscode-java-installer\\binaries\\jdk\\11\\x64\\AdoptOpenJDK-11.msi\"","MSIINSTALLPERUSER=1","ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith","/passive","/l*v \"C:\\Users\\chen\\AppData\\Local\\Temp\\vscode-java-installer\\AdoptOpenJDK-MSI.log\""],"timestamp":"2021-04-23T02:38:07.449Z"}
error: Command failed with exit code 1620: C:\WINDOWS\System32\msiexec.exe /i "C:\Users\chen\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\AdoptOpenJDK-11.msi" MSIINSTALLPERUSER=1 ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v "C:\Users\chen\AppData\Local\Temp\vscode-java-installer\AdoptOpenJDK-MSI.log"
�e�lSb _dk�[ňz�^S0��N�^(uz�^�O�^FUT��|��Nnx��ُ/f N*N	gHe�v  W i n d o w s   I n s t a l l e r   z�^S0
 
  {"shortMessage":"Command failed with exit code 1620: C:\\WINDOWS\\System32\\msiexec.exe /i \"C:\\Users\\chen\\AppData\\Local\\Temp\\vscode-java-installer\\binaries\\jdk\\11\\x64\\AdoptOpenJDK-11.msi\" MSIINSTALLPERUSER=1 ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v \"C:\\Users\\chen\\AppData\\Local\\Temp\\vscode-java-installer\\AdoptOpenJDK-MSI.log\"","command":"C:\\WINDOWS\\System32\\msiexec.exe /i \"C:\\Users\\chen\\AppData\\Local\\Temp\\vscode-java-installer\\binaries\\jdk\\11\\x64\\AdoptOpenJDK-11.msi\" MSIINSTALLPERUSER=1 ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v \"C:\\Users\\chen\\AppData\\Local\\Temp\\vscode-java-installer\\AdoptOpenJDK-MSI.log\"","exitCode":1620,"stdout":"�e�lSb\u0000_dk�[ň\u000bz�^\u0005S\u00020��\u000eN�^(u\u000bz�^�O�^FUT��|\f��Nnx��ُ/f\u0000N*N\tgHe�v \u0000W\u0000i\u0000n\u0000d\u0000o\u0000w\u0000s\u0000 \u0000I\u0000n\u0000s\u0000t\u0000a\u0000l\u0000l\u0000e\u0000r\u0000 \u0000\u000bz�^\u0005S\u00020\n\u0000\r\u0000","stderr":"","failed":true,"timedOut":false,"isCanceled":false,"killed":false,"timestamp":"2021-04-23T02:38:07.663Z"}
verbose: Found JDK {"timestamp":"2021-04-23T02:39:06.542Z"}
verbose: Found JDKs in env.JAVA_HOME {"jdks":["D:\\Program Files\\Java\\jdk1.8.0_181"],"timestamp":"2021-04-23T02:39:06.542Z"}
verbose: Found JDK {"timestamp":"2021-04-23T02:39:06.561Z"}
verbose: Found JDKs in env.PATH {"jdks":["D:\\Program Files\\Java\\jdk1.8.0_181"],"timestamp":"2021-04-23T02:39:06.565Z"}
verbose: Found JDKs in WindowsRegistry {"jdks":["D:\\Program Files\\Java\\jdk1.8.0_181","D:\\Program Files\\Java\\jdk1.8.0_181"],"timestamp":"2021-04-23T02:39:06.726Z"}
verbose: Found JDKs in DefaultLocation {"jdks":[],"timestamp":"2021-04-23T02:39:06.730Z"}
</details>

**Comment by Eskibear** [comment]
The JDK installer might be broken, due to unstable networking.  Can you check the filehash?

Run below command in powershell and share the output here. 
```powershell
Get-FileHash C:\Users\chen\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\AdoptOpenJDK-11.msi
```
It should match with https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.msi.sha256.txt


The workaround is to manually install a [JDK 11+](https://adoptopenjdk.net/) (required by Java Extensions), and re-run our installer.
