### ISSUE TITLE
v0.3.14 error win32 x64

### ISSUE THREAD

**Issue by fabo2641** [microsoft/vscode-java-installer#197]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.14
env:
```
JAVA_HOME: undefined
PATH:
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\windows\system32
C:\windows
C:\windows\System32\Wbem
C:\windows\System32\WindowsPowerShell\v1.0\
C:\windows\System32\OpenSSH\
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\MATLAB\R2020b\bin
C:\Program Files\MATLAB\R2019b\bin
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\dotnet\
C:\Program Files\nodejs\
C:\Users\utente\AppData\Local\Microsoft\WindowsApps
C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3\bin

C:\Users\utente\AppData\Local\Programs\Microsoft VS Code\bin
C:\Users\utente\AppData\Roaming\npm
JDKs:

```
log:
```
[17:03:45] AdoptOpenJDK-11-x64
[17:04:58] Download JDK ... [Completed]
[17:04:58] Install JDK
[17:04:58] Installing AdoptOpenJDK-11-x64...
[17:06:31] Install JDK ... [Completed]
[17:06:31] Configure Java Settings
[17:06:31] Error occurred
[17:06:31] Error: Java Home not found.

```

**Comment by Eskibear** [comment]
Java extensions require JDK 11+ to launch themselves. It looks that the newly installed JDK 11 (not sure if it's successfully installed) was not recognized. You can manually install https://adoptopenjdk.net/ , see if there's any error?

**Comment by Eskibear** [comment]
See #205 
The latest AdoptOpenJDK 11 changed its default installation directory, leading to a false alarm. You can directly install [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack), and it should work out of box.

**Comment by Eskibear** [comment]
Mitigated in v0.3.15, covering new AdoptOpenJDK (Eclipse Temurin JDK). Download link here: https://aka.ms/vscode-java-installer-win
