### ISSUE TITLE
v0.3.14 error win32 x64

### ISSUE THREAD

**Issue by Ac-11** [microsoft/vscode-java-installer#198]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.14
env:
```
JAVA_HOME: undefined
PATH:
C:\Program Files\Google\Chrome\Application
D:\python\Scripts\
D:\python\
C:\ProgramData\Oracle\Java\javapath
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\Git\cmd
C:\Program Files\nodejs\
C:\ProgramData\chocolatey\bin
C:\MinGW\bin
D:\python\Scripts\
D:\python\
C:\Users\Admin\AppData\Local\Microsoft\WindowsApps
C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin
D:\PyCharm Community Edition 2021.1\bin

C:\Users\Admin\AppData\Roaming\npm
C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\bin
C:\Program Files\MongoDB\Server\4.4\bin
C:\Program Files\heroku\bin
JDKs:

```
log:
```
[10:50:02 PM] AdoptOpenJDK-11-x64
[10:52:03 PM] Download JDK ... [Completed]
[10:52:03 PM] Install JDK
[10:52:03 PM] Installing AdoptOpenJDK-11-x64...
[10:52:12 PM] Install JDK ... [Completed]
[10:52:12 PM] Configure Java Settings
[10:52:12 PM] Error occurred
[10:52:12 PM] Error: Java Home not found.

```

**Comment by Eskibear** [comment]
It looks that the newly installed JDK 11 (not sure if it's successfully installed) was not recognized. You can manually install https://adoptopenjdk.net/ , see if there's any error?

**Comment by Eskibear** [comment]
See #205 
The latest AdoptOpenJDK 11 changed its default installation directory, leading to a false alarm. You can directly install [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack), and it should work out of box.

**Comment by Eskibear** [comment]
Mitigated in v0.3.15, covering new AdoptOpenJDK (Eclipse Temurin JDK). Download link here: https://aka.ms/vscode-java-installer-win
