### ISSUE TITLE
v0.3.14 error win32 x64

### ISSUE THREAD

**Issue by mystificator** [microsoft/vscode-java-installer#200]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.14
env:
```
JAVA_HOME: undefined
PATH:
C:\Program Files\Google\Chrome\Application
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin
C:\Program Files\mingw-w64\mingw64\bin
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps
C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code\bin
JDKs:

```
log:
```
[2:50:10 PM] AdoptOpenJDK-11-x64
[2:54:27 PM] Download JDK ... [Completed]
[2:54:27 PM] Install JDK
[2:54:27 PM] Installing AdoptOpenJDK-11-x64...
[2:54:38 PM] Install JDK ... [Completed]
[2:54:38 PM] Configure Java Settings
[2:54:38 PM] Error occurred
[2:54:38 PM] Error: Java Home not found.

```

**Comment by Eskibear** [comment]
See #205 
The latest AdoptOpenJDK 11 changed its default installation directory, leading to a false alarm. You can directly install [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack), and it should work out of box.

**Comment by mystificator** [comment]
> See #205
> The latest AdoptOpenJDK 11 changed its default installation directory, leading to a false alarm. You can directly install [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack), and it should work out of box.

Yep, it worked out fine.
