### ISSUE TITLE
v0.3.14 error win32 x64

### ISSUE THREAD

**Issue by lokesh7644** [microsoft/vscode-java-installer#201]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.14
env:
```
JAVA_HOME: undefined
PATH:
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Users\lokes\AppData\Local\Microsoft\WindowsApps
JDKs:

```
log:
```
[3:54:41 PM] AdoptOpenJDK-11-x64
[4:02:34 PM] Download JDK ... [Completed]
[4:02:34 PM] Install JDK
[4:02:34 PM] Installing AdoptOpenJDK-11-x64...
[4:02:41 PM] Install JDK ... [Completed]
[4:02:41 PM] Configure Java Settings
[4:02:41 PM] Error occurred
[4:02:41 PM] Error: Java Home not found.

```

**Comment by Eskibear** [comment]
See #205 
The latest AdoptOpenJDK 11 changed its default installation directory, leading to a false alarm. You can directly install [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack), and it should work out of box.

**Comment by Eskibear** [comment]
Mitigated in v0.3.15, covering new AdoptOpenJDK (Eclipse Temurin JDK). Download link here: https://aka.ms/vscode-java-installer-win
