### ISSUE TITLE
v0.3.14 error win32 x64

### ISSUE THREAD

**Issue by alissonfr** [microsoft/vscode-java-installer#204]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.14
env:
```
JAVA_HOME: undefined
PATH:
C:\Program Files\Google\Chrome\Application
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Program Files\nodejs\
C:\sqlite3
C:\ProgramData\UNIVALI\Portugol Studio
C:\Program Files\Git\cmd
C:\Users\Alisson\AppData\Local\Microsoft\WindowsApps

C:\Users\Alisson\AppData\Local\Programs\Microsoft VS Code\bin
C:\Users\Alisson\AppData\Roaming\npm
JDKs:

```
log:
```
[22:03:46] AdoptOpenJDK-11-x64
[22:15:01] Download JDK ... [Completed]
[22:15:01] Install JDK
[22:15:01] Installing AdoptOpenJDK-11-x64...
[22:16:08] Install JDK ... [Completed]
[22:16:08] Configure Java Settings
[22:16:09] Error occurred
[22:16:09] Error: Java Home not found.

```

**Comment by Eskibear** [comment]
See #205 
The latest AdoptOpenJDK 11 changed its default installation directory, leading to a false alarm. You can directly install [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack), and it should work out of box.

**Comment by Eskibear** [comment]
Mitigated in v0.3.15, covering new AdoptOpenJDK (Eclipse Temurin JDK). Download link here: https://aka.ms/vscode-java-installer-win
