### ISSUE TITLE
v0.3.15 error darwin x64

### ISSUE THREAD

**Issue by yblaize** [microsoft/vscode-java-installer#236]
:warning:Please attach **$TMPDIR/vscode-java-installer/log.txt** for more details.
version: 0.3.15
env:
```
JAVA_HOME: undefined
PATH:
/usr/bin
/bin
/usr/sbin
/sbin
JDKs:

```
log:
```
[1:21:07 PM] AdoptOpenJDK-11-x64
[1:36:24 PM] Download JDK ... [Completed]
[1:36:24 PM] Install JDK
[1:38:15 PM] Error occurred
[1:38:15 PM] Error: User did not grant permission.

```

**Comment by Eskibear** [comment]
> [1:38:15 PM] Error: User did not grant permission.

It requires admin permission to install a JDK. Did it prompt to ask you for password?

**Comment by yblaize** [comment]
Yes it does ask for a password that's different from my Apple ID and I
don't have it, I think the password is from the first user of the iMac, so
what can I do because I can't access the password?!

**Comment by Eskibear** [comment]
It should be the password of your user account. 

VS Code Java tool require JDK 11 to launch itself. You can install a JDK 11+ by yourself, e.g. from https://adoptopenjdk.net/ .
After installing a valid JDK, just re-run this coding pack. Let me know if that works.

**Comment by yblaize** [comment]
Tried that too but still facing the same error and challenge, asking for
Macintosh HD password which I don't have.

**Comment by Eskibear** [comment]
Then you might have to manually install below components:

- VS Code: https://code.visualstudio.com/Download
- JDK (version >= 11): https://adoptopenjdk.net
- Java Extension Pack: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack

**Comment by yblaize** [comment]
I just tried this too, firstly it accepted VS-Code, when I gave a command
(cmd+shift+P) to install Shell Command: to install code PATH VS-Code, it
came up with the same thing and even when I tried installing JDK 11 too, I
think I need another system I can work with.
