### ISSUE TITLE
v0.3.17 error win32 x64 - no option to install on D:

### ISSUE THREAD

**Issue by mgrazebrook** [microsoft/vscode-java-installer#272]
The key thing here is probably that it seems to be trying to install onto C:. My C partition is barely enough for the operating system so although my user directory is forced to be there (unless I reinstall everything including the OS from scratch), all actual storage is on D:. The installer should in any case have offered me an option to install on D:

:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.17
env:
```
JAVA_HOME: undefined
PATH:
C:\Program Files\Google\Chrome\Application
D:\Program Files\Scripts\
D:\Program Files\
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
D:\Program Files\Python39\Scripts\
D:\Program Files\Python39\
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
D:\Program Files\Git\cmd
D:\Users\micha\.poetry\bin
C:\Users\micha\AppData\Local\Microsoft\WindowsApps
D:\micha\Microsoft VS Code\bin

JDKs:

```
log:
```
[7:57:37 AM] AdoptOpenJDK-11-x64
[7:58:08 AM] Download JDK ... [Completed]
[7:58:08 AM] Install JDK
[7:58:08 AM] Installing AdoptOpenJDK-11-x64...
[7:58:11 AM] Error occurred
[7:58:11 AM] Error: Command failed with exit code 1603: C:\Windows\System32\msiexec.exe /i
 "C:\Users\micha\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\OpenJDK11U-jdk_x64_windows_hotspot_11.0.13_8.msi" MSIINSTALLPERUSER=1 ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v "C:\Users\micha\AppData\Local\Temp\vscode-java-installer\AdoptOpenJDK-MSI.log"

```
[AdoptOpenJDK-MSI.log](https://github.com/microsoft/vscode-java-installer/files/7473176/AdoptOpenJDK-MSI.log)

**Comment by Eskibear** [comment]
To write Java in VS Code, below components are required:
- vscode
- JDK 11 (it's used to launch vscode-java extensions, you can still run your projects with other JDK e.g. Java 8)
- [java extension pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack)

This installer simply helps to install above components with one click (optimized for beginners), but if you have already installed them manually, VS Code should work out-of-box.
