### ISSUE TITLE
Installer v0.3.4 error

### ISSUE THREAD

**Issue by vijavenka** [microsoft/vscode-java-installer#29]
version: 0.3.4
env:
```
os: darwin
arch: x64
PATH: /usr/bin:/bin:/usr/sbin:/sbin
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[13:43:14] AdoptOpenJDK-11-x64
[13:46:22] Download JDK ... [Completed]
[13:46:22] Install JDK
[13:46:35] Install JDK ... [Completed]
[13:46:35] Configure Java Settings
[13:46:36] Error occurred
[13:46:36] Error: Can not add index to parent of type string

```

**Comment by Eskibear** [comment]
Something went wrong when updating your vscode user settings. For macOS, you can manually install [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack), and it should be all set. Let me know if it works.

For better understanding why it went wrong, can you provide your user settings? It's in below path, and remember to wipe sensitive data in the values.
* /Users/<username>/Library/Application Support/Code/User/settings.json
