### ISSUE TITLE
Log file contents

### ISSUE THREAD

**Issue by olivernjeru** [microsoft/vscode-java-installer#303]
info: Started {"timestamp":"2022-01-14T15:52:07.466Z"}
verbose: Ids: {"machineId":"a7a62881df6ece5ee61cbe46cadefba316d8751951a612bc6a76e7bf34553415","sessionId":"addd87e3-ef6d-407b-82fe-9dbb9ccc60461642175523672","timestamp":"2022-01-14T15:52:07.469Z"}
verbose: Packed binaries: {"timestamp":"2022-01-14T15:52:43.398Z"}
verbose: Found JDKs in env.JAVA_HOME {"jdks":[],"timestamp":"2022-01-14T15:52:43.400Z"}
verbose: Found JDKs in env.PATH {"jdks":[],"timestamp":"2022-01-14T15:52:43.416Z"}
verbose: Found JDKs in WindowsRegistry {"jdks":[],"timestamp":"2022-01-14T15:52:44.441Z"}
verbose: Found JDKs in DefaultLocation {"jdks":[],"timestamp":"2022-01-14T15:52:44.444Z"}
verbose: Looking for Code stable x64-user in x64 registry: HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall\{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1 {"timestamp":"2022-01-14T15:52:44.445Z"}
verbose: Code stable x64-user is installed. {"timestamp":"2022-01-14T15:52:44.745Z"}
verbose: Installed components: {"vscode":{"name":"VSCode","homedir":"C:\\Users\\olive\\AppData\\Local\\Programs\\Microsoft VS Code\\","version":"0","displayVersion":"1.54.3","product":{"kind":"user","arch":"x64","edition":"stable","appId":"{771FD6B0-FA20-440A-A002-3B3BAC16DC50}"}},"extensions":[],"timestamp":"2022-01-14T15:52:44.745Z"}
verbose: jdk metadata {"release_name":"jdk-11.0.13+8","release_link":"https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.13%2B8","timestamp":"2021-11-15T16:03:02Z","release":true,"binaries":[{"os":"windows","architecture":"x64","binary_type":"jdk","openjdk_impl":"hotspot","binary_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.13_8.zip","binary_link":"https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.13%2B8/OpenJDK11U-jdk_x64_windows_hotspot_11.0.13_8.zip","binary_size":196666656,"checksum_link":"https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.13%2B8/OpenJDK11U-jdk_x64_windows_hotspot_11.0.13_8.zip.sha256.txt","installer_name":"OpenJDK11U-jdk_x64_windows_hotspot_11.0.13_8.msi","installer_link":"https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.13%2B8/OpenJDK11U-jdk_x64_windows_hotspot_11.0.13_8.msi","installer_size":175078400,"installer_checksum_link":"https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.13%2B8/OpenJDK11U-jdk_x64_windows_hotspot_11.0.13_8.msi.sha256.txt","installer_download_count":382816,"version":"11","version_data":{"openjdk_version":"11.0.13+8","semver":"11.0.13+8"},"heap_size":"normal","download_count":453855,"updated_at":"2021-10-24T09:54:24Z"}],"download_count":1382479}
info: JDK downloaded. {"timestamp":"2022-01-14T16:28:19.645Z"}
verbose: Installing JDK with command: {"msiexec":"C:\\Windows\\System32\\msiexec.exe","args":["/i","\"C:\\Users\\olive\\AppData\\Local\\Temp\\vscode-java-installer\\binaries\\jdk\\11\\x64\\OpenJDK11U-jdk_x64_windows_hotspot_11.0.13_8.msi\"","MSIINSTALLPERUSER=1","ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith","/passive","/l*v \"C:\\Users\\olive\\AppData\\Local\\Temp\\vscode-java-installer\\AdoptOpenJDK-MSI.log\""],"timestamp":"2022-01-14T16:28:19.773Z"}
verbose: Found JDKs in env.JAVA_HOME {"jdks":[],"timestamp":"2022-01-14T16:28:41.276Z"}
verbose: Found JDKs in env.PATH {"jdks":[],"timestamp":"2022-01-14T16:28:41.293Z"}
verbose: Found JDKs in WindowsRegistry {"jdks":[],"timestamp":"2022-01-14T16:28:45.642Z"}
verbose: Found JDKs in DefaultLocation {"jdks":[],"timestamp":"2022-01-14T16:28:45.645Z"}
error: Java Home not found. {"timestamp":"2022-01-14T16:28:45.645Z"}
verbose: Found JDKs in env.JAVA_HOME {"jdks":[],"timestamp":"2022-01-14T16:29:15.957Z"}
verbose: Found JDKs in env.PATH {"jdks":[],"timestamp":"2022-01-14T16:29:15.975Z"}
verbose: Found JDKs in WindowsRegistry {"jdks":[],"timestamp":"2022-01-14T16:29:16.179Z"}
verbose: Found JDKs in DefaultLocation {"jdks":[],"timestamp":"2022-01-14T16:29:16.181Z"}

**Comment by Eskibear** [comment]
thanks for the information, lined to the original issue #302
