### ISSUE TITLE
Installer v0.3.4 error: Java Home not found

### ISSUE THREAD

**Issue by God4you** [microsoft/vscode-java-installer#32]
version: 0.3.4
env:
```
os: win32
arch: x64
PATH: C:\Program Files (x86)\Google\Chrome\Application;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NGX;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\afg_k\AppData\Local\Microsoft\WindowsApps;;C:\Users\afg_k\AppData\Local\Programs\Microsoft VS Code\bin
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[19.27.02] AdoptOpenJDK-11-x64
[19.27.23] Download JDK ... [Completed]
[19.27.23] Install JDK
[19.27.23] install AdoptOpenJDK-11-x64into C:\Users\afg_k\AppData\Local\Programs\AdoptOpenJDK
[19.27.26] Install JDK ... [Completed]
[19.27.26] Configure Java Settings
[19.27.26] Error occurred
[19.27.26] Error: Java Home not found.

```
Please attach **%TEMP%\vscode-java-installer\log.txt** for more details.

**Comment by God4you** [comment]
wtf??

**Comment by Eskibear** [comment]
JDK failed to be recognized after installation. Can you provide `%TEMP%\vscode-java-installer\log.txt` and `%TEMP%\AdoptOpenJDK-MSI.log`?

**Comment by God4you** [comment]
I fixed it. Thanks for the response thought 😊
Fra: Yan Zhang<mailto:notifications@github.com>
Sendt: 13. august 2020 08:32
Til: microsoft/vscode-java-installer<mailto:vscode-java-installer@noreply.github.com>
Cc: God4you<mailto:afg_kakar@live.dk>; Author<mailto:author@noreply.github.com>
Emne: Re: [microsoft/vscode-java-installer] Installer v0.3.4 error (#32)


JDK failed to be recognized after installation. Can you provide %TEMP%\vscode-java-installer\log.txt and %TEMP%\AdoptOpenJDK-MSI.log?
