### ISSUE TITLE
Installer v0.3.4 error

### ISSUE THREAD

**Issue by antonbasic** [microsoft/vscode-java-installer#47]
I have installed java on my machine with sdkman https://sdkman.io/

When using this installer it doesn't recognise this. During setup it tries to install it's own version of java but I get multiple errors that some version of java cannot be launched since it isn't verified by apple. After this it just stops the process with an error.

version: 0.3.4
env:
```
os: darwin
arch: x64
PATH: /usr/bin:/bin:/usr/sbin:/sbin
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[12:56:08] AdoptOpenJDK-11-x64
[12:56:28] Download JDK ... [Completed]
[12:56:28] Install JDK
[12:56:37] Install JDK ... [Completed]
[12:56:37] Configure Java Settings
[12:56:42] Error occurred
[12:56:42] Error: Java Home not found.

```

**Comment by Eskibear** [comment]
This installer use [find-java-home](https://github.com/jsdevel/node-find-java-home) to recognize JDK. As far as I know, Apple suggest to install JDK into `/Library/Java/JavaVirtualMachines/` which should be successfully recognized. I'll investigate sdkman. 

Meanwhile can you provide detailed logs? Should be located in `$TMPDIR/vscode-java-installer/log.txt`
