### ISSUE TITLE
Installer v0.3.6 error

### ISSUE THREAD

**Issue by ritikshb** [microsoft/vscode-java-installer#69]
version: 0.3.6
env:
```
os: win32
arch: x64
PATH: C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot\bin;C:\Program Files\Java\jdk-14.0.2;C:\Program Files\Java\jdk-14.0.1\bin;C:\Users\sharm\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Java\jdk-14.0.1\bin;
JAVA_HOME: C:\Program Files\Java\jdk-14.0.1
```
log:
```
[5:30:49 AM] arch:x64
[5:31:20 AM] Download Visual Studio Code ... [Completed]
[5:31:20 AM] Install Visual Studio Code
[5:31:35 AM] Install Visual Studio Code ... [Completed]
[5:31:35 AM] Configure Java Settings
[5:31:35 AM] Error occurred
[5:31:35 AM] Error:  Please check if you have access to Windows Registry.

```
Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\AdoptOpenJDK-MSI.log** for more details.

**Comment by Eskibear** [comment]
In the last step, it searches Windows Registry for the location of installed vscode. But never mind,  you can open VS Code, install [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack), and it should be all set. Let me know if it doesn't work.

BTW, your `PATH` env is not in a good state.
