### ISSUE TITLE
Misleading user experience when installation completes

### ISSUE THREAD

**Issue by phaumer** [microsoft/vscode-java-installer#7]
The VS Code Java Pack Installer for Windows (using v0.3.1) finishes with a confirmation dialog that has a checkbox pre-selected of now Launching VS Code.  This item and the checkbox are misleading as it assumes that VS Code is now ready to be used.  However, if you have a VS Code extension that is now looking for Java in the path or the JAVA_HOME variable, that extension will fail, because VS Code gets started with an environment that does not know about these entries, yet.  

VS Code has to get started with the new environment variables set and not the context in which the installer was started with.

**Comment by Eskibear** [comment]
Exactly, currently VS Code is launched as a child process of the installer. Known issues are:
* It inherits the environment variables, where newly installed JDK is not included.
* For macOS catalina, it pops up a dialog showing the installer is asking for access to `Documents` folder, but actually it's vscode who needs the access. 

The installer is developed in NodeJS, and VS Code is finally launched by [child_process.spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options). So a potential solution is to find out a way to start VS Code with the updated envs.

One more issue for Windows. In Windows, if you double click the installer to open it, the envs are inherited from process `explorer.exe`. After the installer helps you install the JDK and set JAVA_HOME, if you once again open the installer, the newly installed JDK will not be detected, until you restart `explorer.exe` (by re-login or restart).

**Comment by Eskibear** [comment]
Currently I don't find a way to assign latest envs to subprocess, seems impossible through NodeJS `child_process` module.

**Comment by Eskibear** [comment]
And that's why we actually set `java.home` in vscode's user settings during the installation. Only when you don't have `java.home` set, it tries `JAVA_HOME`, `JDK_HOME`, etc.  See [how redhat.java extension looks for JDK](https://github.com/redhat-developer/vscode-java#setting-the-jdk).

>  that extension will fail, because VS Code gets started with an environment that does not know about these entries, yet.

Thus, it's expected not to fail...

**Comment by phaumer** [comment]
Thanks @Eskibear. I will have our extension look for the java.home setting.

**Comment by Eskibear** [comment]
FYI, vscode-java extension now has an embedded JRE to run itself. So you don't have to look for java.home (which is deprecated).

So I'm closing this issue, though we still fail to find way to launch vscode with latest sysenv.
