### ISSUE TITLE
v0.3.9 error darwin x64

### ISSUE THREAD

**Issue by cce932** [microsoft/vscode-java-installer#84]
:warning:Please attach **$TMPDIR/vscode-java-installer/log.txt** for more details.
version: 0.3.9
env:
```
JAVA_HOME: undefined
PATH:
/usr/bin
/bin
/usr/sbin
/sbin
JDKs:
/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home	defaultLoc
/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home	defaultLoc
```
log:
```
[下午4:05:15] AdoptOpenJDK-11-x64
[下午4:10:30] Download JDK ... [Completed]
[下午4:10:30] Install JDK
[下午4:10:36] Error occurred
[下午4:10:36] Error: User did not grant permission.

```

**Comment by Eskibear** [comment]
> Error: User did not grant permission.

You have JDK 1.8 installed on your machine. VS Code Java requires JDK 11+ to run, so it tried to install an OpenJDK 11 for you, prompting to ask for permission.  Please either install a JDK 11+ manually before you re-run the installer, or grant permission to the installer. 

Please give a try and let me know if that works.
