### ISSUE TITLE
Installer v0.3.5 error

### ISSUE THREAD

**Issue by Yu54088** [microsoft/vscode-java-installer#88]
version: 0.3.5
env:
```
os: win32
arch: x64
PATH: C:\Java\jdk-15\bin;C:\Users\周宇虹\AppData\Local\Microsoft\WindowsApps;G:\vscode\Microsoft VS Code\bin
JAVA_HOME: C:\Java\jdk-15
JDK_HOME: undefined
```
log:
```
[上午12:02:25] arch:x64
[上午12:02:45] Download Visual Studio Code ... [Completed]
[上午12:02:45] Install Visual Studio Code
[上午12:03:08] Install Visual Studio Code ... [Completed]
[上午12:03:08] Configure Java Settings
[上午12:03:08] Error occurred
[上午12:03:08] Error:  Please check if you have access to Windows Registry.

```
Please attach **%TEMP%\vscode-java-installer\log.txt** for more details.

**Comment by Eskibear** [comment]
> [上午12:03:08] Error:  Please check if you have access to Windows Registry.

Because you don't have access to the Registry, the installer failed to detect where you installed vscode, thus could not further configure related settings.

Workaround is, you install [Java extension pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) by your own.

**Comment by Eskibear** [comment]
I'm closing it as VS Code detection mechanism has been improved.
