### ISSUE TITLE
v0.3.10 error win32 x64

### ISSUE THREAD

**Issue by arusmiati** [microsoft/vscode-java-installer#90]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.10
env:
```
JAVA_HOME: C:\Program Files\Java\jdk-14.0.2\bin\jre1.8.0_261
PATH:
C:\Program Files (x86)\Google\Chrome\Application
C:\Program Files\Java\jdk-14.0.2\bin
C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin
G:\Java\jre1.8.0_261\bin
C:\Users\VITARACOM\AppData\Local\Programs\Microsoft VS Code\bin
C:\Program Files\Java\jdk-14.0.2\bin
C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin

JDKs:
C:\Program Files\Java\jdk-14.0.2	env.PATH,env.PATH,WindowsRegistry,DefaultLocation
```
log:
```
[2:03:59 PM] Configure Java Settings
[2:03:59 PM] Error occurred
[2:03:59 PM] Error: Can not add index to parent of type string

```

**Comment by Eskibear** [comment]
> JAVA_HOME: C:\Program Files\Java\jdk-14.0.2\bin\jre1.8.0_261

This is wrong. please remove it from your environment varible, or set it to `C:\Program Files\Java\jdk-14.0.2`. To get Java working in vscode, you can install [Java extension pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) by your own. 

> [2:03:59 PM] Error: Can not add index to parent of type string

Can you share full content of your user settings? Then we may figure out what happened.
