### ISSUE TITLE
v0.3.10 error win32 x64

### ISSUE THREAD

**Issue by bracealround** [microsoft/vscode-java-installer#95]
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.10
env:
```
JAVA_HOME: undefined
PATH:
C:\Program Files (x86)\Google\Chrome\Application
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
E:\Java\bin
E:\Git\cmd
C:\MinGW\bin
C:\Users\User\AppData\Local\Programs\Python\Python38-32\Scripts\
C:\Users\User\AppData\Local\Programs\Python\Python38-32\
C:\Users\User\AppData\Local\Microsoft\WindowsApps
C:\Users\User\AppData\Local\Programs\Python\Python38-32
E:\Microsoft VS Code\bin
E:\CodeBlocks\MinGW\bin

JDKs:
E:\Java	env.PATH
C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot	DefaultLocation
```
log:
```
[11:04:17 AM] Configure Java Settings
[11:04:17 AM] Error occurred
[11:04:17 AM] Error: EPERM: operation not permitted, write

```

**Comment by Eskibear** [comment]
> [11:04:17 AM] Error: EPERM: operation not permitted, write

It failed to update `java.home` in your user settings. Do you have write permission under folder `C:\Users\<username>\AppData\Roaming\Code\User`?

Workaround is that, you install[ Java extension pack ](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack)manually, and set `java.home` to "C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot"
